### ISSUE TITLE
Documentation issues (pre-release)

### ISSUE THREAD

**Issue by rhnvrm** [zerodha/cppkiteconnect#5]
Opening this thread for collecting any documentation related issues/suggestions before the first release.

cc @ranjanrak, you can mention the issues you spotted here.

**Comment by bhumitattarde** [comment]
Documentation will need to be updated (see #7), but I suggest accumulating changes and updating the docs at once.

**Comment by ranjanrak** [comment]
Sure @rhnvrm. At inital glance, i saw below few issues: 

1> [profile()](https://kite.trade/docs/cppkiteconnect/structkiteconnect_1_1userProfile.html) response is missing ```user_id``` and ```meta(demat_consent)``` fields.And phone number field should be removed.
The actual profile response is:
```{'user_id': '...', 'user_type': '...', 'email': '.....', 'user_name': '....', 'user_shortname': '....', 'broker': '.....', 'exchanges': [......], 'products': [.....], 'order_types': [.....], 'avatar_url': '......', 'meta': {'demat_consent': '.....'}```
2> [getAPIKey()](https://kite.trade/docs/cppkiteconnect/classkiteconnect_1_1kite.html#a31b547167ea310dc3a0ca6715836f39a), needs better defination. Instead of ```get set API key```, maybe you can phrase it as ```fetch current app api key```.
3> [setAPIKey()](https://kite.trade/docs/cppkiteconnect/classkiteconnect_1_1kite.html#af45c2c0f5dcfc284b723bcfbbd94317a), you can define arg here. 
4> Also, I see parameters definition is missing randomly for many fields in few functions. Example, check [placeOrder()  
](https://kite.trade/docs/cppkiteconnect/classkiteconnect_1_1kite.html#aafd9dd5ddad847231d1af96d9f724720), parameter details ```orderType, validity,  tag, etc ``` fields definition are missing. Same for [placeMFOrder()](https://kite.trade/docs/cppkiteconnect/classkiteconnect_1_1kite.html#a585f951df6f5c54dcbcdf9b1dd8f3606), ```quantity, symbol,  amount, tag``` definition is missing.

**Comment by bhumitattarde** [comment]
I'll look into 2 & 3.
1. I've wrote response structs referring to mock responses from go and/or python client. Both client's `profile.json` file doesn't have a `user_id` or `meta` field. If `profile` struct is to be updated, appropriate mock responses will need to be set as well. 
4. They were left out on purpose since I felt arguments like `amount`, `tag`, `validity` were pretty self-explanatory. I can update their descriptions if it's needed. Let me know.

**Comment by ranjanrak** [comment]
> They were left out on purpose since I felt arguments like amount, tag, validity was pretty self-explanatory. I can update their descriptions if it's needed. Let me know.

Yes, even if arguments are self-explanatory, you need to add an explanation for them. Maybe you can use the same definition here as mentioned in our [API documentation](https://kite.trade/docs/connect/v3/orders/#glossary-of-constants).

**Comment by bhumitattarde** [comment]
I've updated documentation. Check linked PR and let me know changes to be made, if any.

Both client's `profile.json` still doesn't show either of those fields for me. I checked the following files:
1. https://github.com/zerodha/pykiteconnect/blob/master/tests/mock_responses/profile.json
2. https://github.com/zerodha/gokiteconnect/blob/master/mock_responses/profile.json
3. https://github.com/zerodha/gokiteconnect/blob/develop/mock_responses/profile.json

Also, could you please create a separate issue for this since it isn't documentation related?

**Comment by bhumitattarde** [comment]
See #19 regarding `user_id` & `meta` fields.

**Comment by rhnvrm** [comment]
kite.trade/docs/cppkiteconnect is updated

**Comment by bhumitattarde** [comment]
@rhnvrm Could you please update it again once #21 merged?

**Comment by rhnvrm** [comment]
@bhumitattarde, updated :+1:
